### ISSUE TITLE
Estou com um problema na hora que eu inicio o bot ele da erro de lavalink (localhost)

### ISSUE THREAD

**Issue by RotivV** [zulybot/zuly#126]
https://user-images.githubusercontent.com/72051608/158020923-d333b686-b46c-4223-9fa4-8c82e58d60cb.png

https://user-images.githubusercontent.com/72051608/158020924-0faaf158-eb78-41d7-b4ba-ecd46c18fb02.png

**Comment by andrelucaas** [comment]
você tem que rodar um servidor lavalink.
